apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: your-pipeline-run
spec:
  pipelineRef:
    name: docker-build-and-push-pipeline
  params:
    - name: repo-url
      value: 'https://github.com/kranthi619/Budget-app.git'
    - name: repo-revision
      value: 'master'
    - name: image-name
      value: 'budget-app'
    - name: docker-hub-username
      value: 'kranthi619'
